name: ci

# On every push this script is executed
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      - name: Build Zola
        run: zola build

      - name: Encrypt private content
        uses: jhlzlove/ssg-encrypt@main
        with:
          selector: "#encryptedBox"
          content-selector: "#articleContent"
        env:
          SITE_ENCRYPT_PASSWORDS: ${{ secrets.ENCRYPT_PASSWORDS }}

      - name: Build Pagefind index
        run: |
          wget -O pagefind.tar.gz \
                      https://github.com/Pagefind/pagefind/releases/download/v1.5.2/pagefind_extended-v1.5.2-x86_64-unknown-linux-musl.tar.gz
          tar -xzf pagefind.tar.gz
          ./pagefind_extended \
                      --site public

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
